import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {api,ACCOUNT} from '../gym-badge-scaling/api.mjs';
const root=process.cwd(),out=path.join(root,'output/evolution-30-journeys');const rows=JSON.parse(fs.readFileSync(out+'/journeys.json'));const source=path.join(root,'output/evolution-static-100-2026-09-12/approved-selected-30-90-images');
const errors=[],check=(v,m)=>{if(!v)errors.push(m)};const dependencies=new Set(['sections/evolution-ad-journey.liquid','layout/evolution-rainbow-paws.liquid']);
function walk(file){const s=fs.readFileSync(path.join(root,file),'utf8');for(const m of s.matchAll(/['"]([^'"]+)['"]\s*\|\s*asset_url/g)){const f='assets/'+m[1];check(fs.existsSync(f),'Missing '+f);dependencies.add(f)}for(const m of s.matchAll(/{%[-]?\s*render\s+['"]([^'"]+)['"]/g)){const f='snippets/'+m[1]+'.liquid';check(fs.existsSync(f),'Missing '+f);if(!dependencies.has(f)&&fs.existsSync(f)){dependencies.add(f);walk(f)}}}
for(const f of [...dependencies])walk(f);
for(const f of fs.readdirSync('assets').filter(f=>/^evo-portrait-|^evo-campaign-customer-0[2-6]/.test(f)))dependencies.add('assets/'+f);
const ads=rows.map(r=>{dependencies.add(r.template);const t=JSON.parse(fs.readFileSync(r.template));check(t.sections.main.settings.journey_id===r.slug,'Wrong template '+r.id);const images=r.images.map(i=>{const file=path.join(source,i.file),b=fs.readFileSync(file),sha=crypto.createHash('sha256').update(b).digest('hex');check(sha===i.sha256,'Changed approved image '+i.file);return{placement:i.placement,file,width:b.readUInt32BE(16),height:b.readUInt32BE(20),sha256:sha}});const u=new URL(r.url);u.searchParams.set('variant','47968551764073');u.searchParams.set('utm_source','meta');u.searchParams.set('utm_medium','paid_social');u.searchParams.set('utm_campaign','evolution_full_set_20260905');u.searchParams.set('utm_content',r.slug);return{id:r.id,name:'EC | '+r.id+' | '+r.name+' | Journey R03',primary:r.settings.hero_body,headline:r.settings.cta_label,description:'Complete 8-plush set · Free shipping',url:u.href,images}});
const meta=api();const [campaign,adset,existing,product]=await Promise.all([meta.get('52591498796722',{fields:'id,account_id,name,status,daily_budget,bid_strategy'}),meta.get('52591498798722',{fields:'id,campaign_id,status,bid_amount,optimization_goal,promoted_object,targeting,attribution_spec'}),meta.all('52591498798722/ads',{fields:'id,name,status,effective_status',limit:100}),fetch('https://zenkaiclothing.com/products/evolution-companions-complete-8-plush-collector-set.js').then(r=>r.json())]);
check('act_'+campaign.account_id===ACCOUNT,'Wrong account');check(adset.campaign_id===campaign.id,'Wrong ad set parent');check(campaign.bid_strategy==='COST_CAP','Bid strategy changed');check(adset.promoted_object?.custom_event_type==='PURCHASE','Wrong optimization');const variant=product.variants.find(v=>String(v.id)==='47968551764073');check(variant?.available,'Variant unavailable');check(variant?.price===16000,'Price differs from approved ads');
const result={at:new Date().toISOString(),mode:'read-only',errors,campaign,adset,existingAds:existing,product:{id:product.id,title:product.title,variant},proposedBudget:1000,ads,themeFiles:[...dependencies].sort(),pending:'User page review, live theme dependency comparison, publication and live verification, then ad creation/activation and budget update'};
fs.writeFileSync(out+'/preflight.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({errors,currentBudget:Number(campaign.daily_budget)/100,costCap:Number(adset.bid_amount)/100,existingAds:existing.length,activeAds:existing.filter(x=>x.status==='ACTIVE').length,newAds:ads.length,images:ads.reduce((a,x)=>a+x.images.length,0),themeFiles:dependencies.size,price:variant?.price/100}));if(errors.length)process.exitCode=1;
