import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const {chromium}=require('/Users/vishnup/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=process.cwd(),out=path.join(root,'output/evolution-30-journeys');await fs.mkdir(out+'/qa',{recursive:true});const rows=JSON.parse(await fs.readFile(out+'/journeys.json'));
const server=http.createServer(async(req,res)=>{try{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'application/javascript','.webp':'image/webp','.png':'image/png','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:'/Users/vishnup/Library/Caches/ms-playwright/chromium-1229/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'});const results=[],failures=[];const live=process.argv.includes('--live');
try{for(const width of [390,1440]){const page=await browser.newPage({viewport:{width,height:900}});for(const x of rows){await page.goto(live?x.url:base+'/output/plush-design-review/pages/'+x.slug+'.html',{waitUntil:'domcontentloaded'});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('main img[src]')].map(i=>{i.loading='eager';return i.decode().catch(()=>{})}))});const r=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.querySelectorAll('main img[src]')].filter(i=>!i.naturalWidth).map(i=>i.src),form:Object.fromEntries(new FormData(document.querySelector('form'))),order:[...document.querySelectorAll('.fg-page>section')].map(e=>e.classList[0].replace('fg-','')).filter(n=>['moods','personality','scale','closeup'].includes(n)),h1:document.querySelector('h1').textContent.trim(),cards:document.querySelectorAll('.fg-mood-card').length,cta:document.querySelector('[data-ec-main-cta]').getBoundingClientRect().height}));if(r.overflow||r.broken.length||r.form.id!=='47968551764073'||r.form['properties[_zk_landing_view]']!==x.slug||r.cards!==8||r.cta<44||r.order.join()!==x.order.join())failures.push({id:x.id,width,...r});
await page.screenshot({path:out+'/qa/'+(live?'live-':'')+x.id+'-'+width+'.png',fullPage:true});results.push({id:x.id,width,...r});
if(x.id==='ST15'){await page.locator('[data-ec-zoom]').first().click();if(!await page.locator('dialog').evaluate(e=>e.open))failures.push({id:x.id,width,error:'zoom failed'});await page.locator('[data-ec-close]').click();await page.locator('.fg-faq details').first().click();if(!await page.locator('.fg-faq details').first().evaluate(e=>e.open))failures.push({id:x.id,width,error:'faq failed'});}
}await page.close();console.log('Verified',rows.length,'pages at',width)}
const page=await browser.newPage();await page.goto(base+'/output/evolution-30-journeys/index.html');await page.locator('[data-page]').first().click();if(!await page.locator('dialog').evaluate(e=>e.open))failures.push({error:'review dialog'});await page.locator('#close').click();await page.locator('#search').fill('I04');if(await page.locator('article:visible').count()!==1)failures.push({error:'filter'});
await fs.writeFile(out+'/qa/'+(live?'live-results.json':'results.json'),JSON.stringify({results,failures},null,2));console.log(JSON.stringify({checks:results.length,failures}));}finally{await browser.close();server.close();}if(failures.length)process.exitCode=1;
