import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const raw=fs.readFileSync(new URL('../../snippets/impostors-ab-router.liquid',import.meta.url),'utf8');
const js=raw.split('<script>')[1].split('</script>')[0].replace('{{ impostors_ab_enabled | json }}','true');
function run(url,{stored=null,rand=0,storageFails=false}={}) {let redirect=null,formInputs=[];const storage=new Map(stored?[['zk:impostors_design_20260913_v1',JSON.stringify(stored)]]:[]);const doc={readyState:'complete',querySelectorAll:()=>[{querySelector:()=>null,appendChild:i=>formInputs.push(i)}],createElement:()=>({})};const w={};vm.runInNewContext(js,{URL,Uint32Array,Date,JSON,window:w,document:doc,crypto:{getRandomValues:a=>{a[0]=rand;a[1]=123;}},location:{href:url,replace:u=>redirect=u},localStorage:{getItem:k=>{if(storageFails)throw Error();return storage.get(k)},setItem:(k,v)=>storage.set(k,v)}});return {redirect,storage,w,formInputs};}
const base='https://zenkaiclothing.com/products/little-impostors-complete-9-plush-collector-set';
for(const [rand,variant] of [[0,'original'],[4294967295,'current']]){const r=run(base+'?utm_source=meta&fbclid=keep',{rand});assert.equal(new URL(r.redirect).searchParams.get('view'),'impostors-ab-'+variant);assert.equal(new URL(r.redirect).searchParams.get('fbclid'),'keep');const a=JSON.parse([...r.storage.values()][0]);const done=run(r.redirect,{stored:a,rand:variant==='current'?0:4294967295});assert.equal(done.redirect,null);assert.equal(done.w.zenkaiImpostorsExperiment.variant,variant);assert.equal(done.formInputs.length,3);assert.equal(run(base,{stored:a}).w.zenkaiImpostorsExperiment,undefined);assert.equal(new URL(run(base,{stored:a}).redirect).searchParams.get('view'),'impostors-ab-'+variant);}
assert.equal(run(base,{storageFails:true}).redirect,null);
for(const suffix of ['?view=impostors-ab-original&ab_preview=1','?view=impostors-ab-current','?view=impostors-other-journey','?preview_theme_id=123'])assert.equal(run(base+suffix).redirect,null);
console.log('PASS: equal-arm routing, preserved ad parameters, durable assignment, no loop, form labels, explicit previews, unrelated journeys, and storage failure.');
